#!/usr/bin/env python
# -*- coding: utf-8 -*-

from __future__ import absolute_import, unicode_literals

import os
from builtins import dict

from future import standard_library
from pyload.core import datatype
from pyload.core.datatype.debug import enums
from pyload.utils.fs import lopen

standard_library.install_aliases()


# generate js enums
def main():
    print("generating apitypes.js")

    file = os.path.join(PACKDIR, 'app', 'scripts', 'utils', 'apitypes.js')
    with lopen(file, 'wb') as fp:
        fp.write("""// Autogenerated, do not edit!
/*jslint -W070: false*/
define([], function() {
\t'use strict';
\treturn {
""")
        for name in enums:
            enum = getattr(datatype, name)
            values = dict((attr, getattr(enum, attr))
                          for attr in dir(enum) if not attr.startswith("_"))
            fp.write("\t\t{0}: {1},{2}".format(name, values, os.linesep))
        fp.write("\t};{0}});".format(os.linesep))


if __name__ == '__main__':
    main()
